upstream_original=https://github.com/NexAlloy/NexAlloy
upstream_fork=https://github.com/gnadgnaoh/NexAlloy-XES
channel=release
release_tag=v1.0
release_commit=fa5b56c
payload_version_name=2.0.109-compat1
payload_version_code=109
runtime_api=1
google_photos_excluded=true
